FROM karalabe/xgo-latest

#RUN export GOPROXY="https://mirrors.aliyun.com/goproxy/"
#RUN git config --global http.proxy "https://mirrors.aliyun.com/goproxy/"
#RUN git config --global https.proxy "https://mirrors.aliyun.com/goproxy/"

ENV GOPROXY="https://goproxy.cn,direct"


